package view;

import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import java.io.File;
import java.io.IOException;

import java.util.Map;
import java.util.PriorityQueue;
import java.util.TreeMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.*;

import javax.imageio.ImageIO;

import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

public class TeacherRes extends javax.swing.JFrame {

    Person person;
    String fullname;
    String dOb;
    String address;
    String gender;
    String username;
    String password;
    File file;
    String image;

    public TeacherRes(String fullname, String dOb, String address, String gender, String username, String password) {
        this.fullname = fullname;
        this.dOb = dOb;
        this.address = address;
        this.gender = gender;
        this.username = username;
        this.password = password;
        initComponents();
        this.setResizable(false);
        this.addBT.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                boolean donthave = true;  // check có giáo viên nào đã nhận subject đó
                String subject = subjectCBB.getItemAt(subjectCBB.getSelectedIndex());
                for (Map.Entry<Integer, Teacher> entry : SandTDAO.storeTInfor.entrySet()) {
                    if (entry.getValue().classInCharge == Integer.parseInt(cicCBB.getItemAt(cicCBB.getSelectedIndex())) && entry.getValue().subject.equalsIgnoreCase(subject)) {
                        donthave = false;
                        break;
                    }
                }
                // tạo account cho giáo viên
                if (donthave) {
                    if (image == null) {
                        image = "C:/Users/DELL/Documents/NetBeansProjects/ProjectCSE203/Images/defaultimage.jpg";
                    }
                    person = new Teacher(SandTDAO.storeTInfor.size() + 1, fullname, image, dOb,
                            address, gender, username,
                            password, Integer.parseInt(cicCBB.getItemAt(cicCBB.getSelectedIndex())), degreeCBB.getItemAt(degreeCBB.getSelectedIndex()), "Teacher", subject);
                    SandTDAO.storeTInfor.put(person.id, (Teacher) person);
                    TreeMap<String, Person> temp = new TreeMap<>();
                    temp.put(password, person);
                    Login.personAccount.put(username, temp);
                    JOptionPane.showMessageDialog(rootPane, "Create Successfully");
                    TeacherRes.this.setVisible(false);
                } else {
                    warningError("There is another teacher being responsible for this class");
                }

            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */


    private void warningError(String message) {
        String title = "Warning";
        String content = message;
        JOptionPane.showMessageDialog(rootPane, content, title, JOptionPane.ERROR_MESSAGE);
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cicLabel = new javax.swing.JLabel();
        degreeCBB = new javax.swing.JComboBox<>();
        subjectLabel = new javax.swing.JLabel();
        subjectCBB = new javax.swing.JComboBox<>();
        addBT = new Swing.MyButton();
        imageLabel = new javax.swing.JLabel();
        registerLabel = new javax.swing.JLabel();
        degreeLabel = new javax.swing.JLabel();
        cicCBB = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(154, 182, 207));

        cicLabel.setText("Class In Charge");

        degreeCBB.setBackground(new java.awt.Color(154, 182, 207));
        degreeCBB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Bachelor", "Engineering" }));

        subjectLabel.setText("Subject");

        subjectCBB.setBackground(new java.awt.Color(154, 182, 207));
        subjectCBB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Maths", "Chemistry", "Physics" }));
        subjectCBB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subjectCBBActionPerformed(evt);
            }
        });

        addBT.setBackground(new java.awt.Color(0, 58, 98));
        addBT.setForeground(new java.awt.Color(255, 255, 255));
        addBT.setText("Add");
        addBT.setColor(new java.awt.Color(0, 58, 98));
        addBT.setColorOver(new java.awt.Color(0, 58, 98));
        addBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBTActionPerformed(evt);
            }
        });

        imageLabel.setBackground(new java.awt.Color(0, 0, 0));
        imageLabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        imageLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        imageLabel.setText("Add Image");
        imageLabel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        imageLabel.setMaximumSize(new java.awt.Dimension(145, 126));
        imageLabel.setMinimumSize(new java.awt.Dimension(145, 126));
        imageLabel.setPreferredSize(new java.awt.Dimension(145, 126));
        imageLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                imageLabelMouseClicked(evt);
            }
        });

        registerLabel.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        registerLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        registerLabel.setText("Register");
        registerLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        degreeLabel.setText("Degree");

        cicCBB.setBackground(new java.awt.Color(154, 182, 207));
        cicCBB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "10", "11", "12" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(registerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(addBT, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(subjectCBB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cicCBB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(degreeCBB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cicLabel)
                            .addComponent(degreeLabel)
                            .addComponent(subjectLabel))))
                .addGap(43, 43, 43)
                .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(registerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(degreeLabel)
                            .addComponent(degreeCBB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cicLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cicCBB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 20, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(subjectLabel)
                            .addComponent(subjectCBB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(addBT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void addBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addBTActionPerformed

    private void imageLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_imageLabelMouseClicked
        try {
            // TODO add your handling code here:
            JFileChooser jfc = new JFileChooser("C:/Users/DELL/Documents/NetBeansProjects/ProjectCSE203/Images");
            jfc.showOpenDialog(null);
            if (jfc.getSelectedFile() == null) {
                file = new File("C:/Users/DELL/Documents/NetBeansProjects/ProjectCSE203/Images/defaultimage.jpg");
            } else {
                file = jfc.getSelectedFile();
            }
            Image img = ImageIO.read(file);
            imageLabel.setText("");
            this.image = file.getPath();
            imageLabel.setIcon(new ImageIcon(img.getScaledInstance(imageLabel.getWidth(), imageLabel.getHeight(), 0)));
        } catch (IOException ex) {
            System.out.println("Error: " + ex.toString());
        }
    }//GEN-LAST:event_imageLabelMouseClicked

    private void subjectCBBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subjectCBBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subjectCBBActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TeacherRes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TeacherRes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TeacherRes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeacherRes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new TeacherRes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Swing.MyButton addBT;
    private javax.swing.JComboBox<String> cicCBB;
    private javax.swing.JLabel cicLabel;
    private javax.swing.JComboBox<String> degreeCBB;
    private javax.swing.JLabel degreeLabel;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel registerLabel;
    private javax.swing.JComboBox<String> subjectCBB;
    private javax.swing.JLabel subjectLabel;
    // End of variables declaration//GEN-END:variables
}
